### ISSUE TITLE
verifyChksums shows hash but not the file name when a hash difference is found

### ISSUE THREAD

**Issue by skr1pz** [newodahs/integrityChk#1]
**# Requested Enhancement / Issue:**

When a difference is detected it shows the hash but not the file name i.e.:

[user@server ~]# ./integrityChk.sh -v
Please enter the secret key: 
Clearing /tmp/os_chk/composite.hash
Calculating checksum for /bin
Calculating checksum for /sbin
Calculating checksum for /usr/bin
Calculating checksum for /usr/sbin
Calculating checksum for /usr/local/bin
Calculating checksum for /etc
Calculating checksum for /usr/local/etc
Differences found! Checking individual hashes...
Examining file hashes for bin
Showing diff for directory bin:
[ changed
        SHA-256 expected **41xxxxxxxxxxxxxxxxxxcd7thisChecksumbed474091** found 4177052090eaa632802cd724blahBlahRedCatxxxxxxxxxxxxxxxxxxxxxx1
Examining file hashes for etc
Examining file hashes for sbin
Examining file hashes for usr/bin
Examining file hashes for usr/local/bin
Examining file hashes for usr/local/etc
Examining file hashes for usr/sbin

Please add logic to substring search for the file name that corresponds with the first hash listed above.

**# Recreate:**
- run integrityChk.sh with -g argument, create key
- extract osChk.tgz 
- in this example - edit 'cat' hash in 'hash/_bin_hash.dir'
- then edit bin hash in 'hash/composite.hash'
- run integrityChk.sh with -v argument, enter key

**Comment by newodahs** [comment]
Can you do me a favor and pass me the diff file for this particular run?  You should be able to find them under /tmp/os_chk/ in the version you're running.

**Comment by skr1pz** [comment]
check Skype

**Comment by newodahs** [comment]
Thanks, I'll dig in, in the AM.

**Comment by newodahs** [comment]
OK, So there is probably a screen-size issue here, but to give you a run down based on what I see in the diff file you sent me:
1. The hash you changed was actually for '[' (aka 'test') and not 'cat'
2. The diff output is correct: it is stating that '[' changed, what it was expecting for a hash and what it actually received.

It looks a bit funny, I believe, due to how less is printing out to the screen; I'll play around a bit with getting a better output format (maybe get rid of less altogether and just format it myself).  I'll keep you updated.

**Comment by skr1pz** [comment]
Sure, I see that now after re-testing; the corresponding file name is shown.
